const products=[
 {id:1,name:'Флорариум «Тихий лес»',price:6900,category:'terrarium',image:'assets/terrarium-01.jpg',stock:true,badge:'Хит',description:'Тропическая композиция с фиттонией и живым мхом в стеклянном сосуде.'},
 {id:2,name:'Флорариум «Розовый кварц»',price:5400,category:'terrarium',image:'assets/terrarium-02.jpg',stock:true,badge:'Новинка',description:'Нежная композиция с природным кварцем и компактными влаголюбивыми растениями.'},
 {id:3,name:'Флорариум «Утренний сад»',price:7800,category:'terrarium',image:'assets/terrarium-03.jpg',stock:false,description:'Закрытая экосистема с многослойным грунтом. Изготовим похожую за 3–5 дней.'},
 {id:4,name:'Фиттония для мини-сада',price:650,category:'plant',image:'assets/terrarium-04.jpg',stock:true,description:'Компактное растение с яркими прожилками, адаптированное для закрытых композиций.'},
 {id:5,name:'Набор «Собери свой лес»',price:2900,category:'kit',image:'assets/terrarium-05.jpg',stock:true,badge:'−10%',description:'Сосуд, дренаж, грунт, мох, декор и подробная инструкция в одной коробке.'},
 {id:6,name:'Флорариум «Сказочный мох»',price:6200,category:'terrarium',image:'assets/terrarium-06.jpg',stock:true,description:'Лесная композиция с мягким рельефом и миниатюрным декором.'},
 {id:7,name:'Живой мох, упаковка 200 г',price:490,category:'plant',image:'assets/terrarium-07.jpg',stock:true,description:'Свежий стабилизированный для транспортировки мох для декора и мини-садов.'},
 {id:8,name:'Набор «Домашний ботаник»',price:3400,category:'kit',image:'assets/terrarium-08.jpg',stock:false,description:'Расширенный набор для самостоятельной сборки флорариума. Скоро снова в наличии.'},
 {id:9,name:'Флорариум «Изумрудный берег»',price:5900,category:'terrarium',image:'assets/terrarium-01.jpg',stock:true,badge:'Новинка',description:'Композиция с папоротником, мхом и светлым камнем в округлом сосуде.'},
 {id:10,name:'Флорариум «Тропический дождь»',price:8600,category:'terrarium',image:'assets/terrarium-02.jpg',stock:true,description:'Высокая закрытая композиция для интерьера с мягким рассеянным светом.'},
 {id:11,name:'Флорариум «Горная тропа»',price:7200,category:'terrarium',image:'assets/terrarium-03.jpg',stock:true,description:'Миниатюрный горный ландшафт с натуральным камнем и живым мхом.'},
 {id:12,name:'Флорариум «Лес после дождя»',price:8100,category:'terrarium',image:'assets/terrarium-04.jpg',stock:false,description:'Влажная лесная композиция с выразительной фактурой и глубокими оттенками зелени.'},
 {id:13,name:'Флорариум «Белая скала»',price:6500,category:'terrarium',image:'assets/terrarium-05.jpg',stock:true,description:'Лаконичный сад с белым кварцем и компактными тропическими растениями.'},
 {id:14,name:'Флорариум «Долина папоротников»',price:9300,category:'terrarium',image:'assets/terrarium-06.jpg',stock:true,badge:'Хит',description:'Объёмная композиция с несколькими видами миниатюрных папоротников.'},
 {id:15,name:'Флорариум «Северный мох»',price:4800,category:'terrarium',image:'assets/terrarium-07.jpg',stock:true,description:'Спокойная зелёная композиция, построенная вокруг природной фактуры мха.'},
 {id:16,name:'Флорариум «Лунный камень»',price:7600,category:'terrarium',image:'assets/terrarium-08.jpg',stock:true,description:'Контрастная композиция с тёмным грунтом и светлым декоративным камнем.'},
 {id:17,name:'Флорариум «Тёплый туман»',price:7100,category:'terrarium',image:'assets/terrarium-01.jpg',stock:false,description:'Закрытый мини-сад с мягкими линиями и устойчивым внутренним микроклиматом.'},
 {id:18,name:'Флорариум «Сад на рассвете»',price:9900,category:'terrarium',image:'assets/terrarium-02.jpg',stock:true,badge:'Премиум',description:'Крупная авторская композиция с многоуровневым рельефом.'},
 {id:19,name:'Флорариум «Маленькая планета»',price:5700,category:'terrarium',image:'assets/terrarium-03.jpg',stock:true,description:'Компактная самодостаточная экосистема в сферическом сосуде.'},
 {id:20,name:'Флорариум «Зелёный остров»',price:6800,category:'terrarium',image:'assets/terrarium-04.jpg',stock:true,description:'Сочная тропическая композиция для рабочего стола или открытой полки.'},
 {id:21,name:'Флорариум «Каменный ручей»',price:8400,category:'terrarium',image:'assets/terrarium-05.jpg',stock:true,description:'Мини-сад с каменной линией, напоминающей русло лесного ручья.'},
 {id:22,name:'Флорариум «Малахит»',price:6300,category:'terrarium',image:'assets/terrarium-06.jpg',stock:false,description:'Насыщенная зелёная композиция с декоративной минеральной крошкой.'},
 {id:23,name:'Флорариум «Лесной домик»',price:8800,category:'terrarium',image:'assets/terrarium-07.jpg',stock:true,badge:'Выбор мастера',description:'Сюжетная композиция с маленьким домиком среди мха и растений.'},
 {id:24,name:'Флорариум «Воздушный сад»',price:5200,category:'terrarium',image:'assets/terrarium-08.jpg',stock:true,description:'Светлая минималистичная композиция с большим количеством воздуха.'},
 {id:25,name:'Флорариум «Зелёный купол»',price:10900,category:'terrarium',image:'assets/terrarium-01.jpg',stock:true,description:'Большой закрытый сад под стеклянным куполом для просторного интерьера.'},
 {id:26,name:'Флорариум «Мшистый склон»',price:6100,category:'terrarium',image:'assets/terrarium-02.jpg',stock:true,description:'Рельефная композиция с несколькими видами мха и природным камнем.'},
 {id:27,name:'Флорариум «Речной берег»',price:7400,category:'terrarium',image:'assets/terrarium-03.jpg',stock:false,description:'Миниатюрный берег с галькой, мхом и влаголюбивыми растениями.'},
 {id:28,name:'Флорариум «Тайная тропа»',price:8200,category:'terrarium',image:'assets/terrarium-04.jpg',stock:true,description:'Атмосферная лесная композиция с извилистой дорожкой из мелкого камня.'},
 {id:29,name:'Фиттония беложильчатая',price:590,category:'plant',image:'assets/terrarium-04.jpg',stock:true,description:'Миниатюрная фиттония с контрастным рисунком для влажных композиций.'},
 {id:30,name:'Фиттония розовая',price:620,category:'plant',image:'assets/terrarium-02.jpg',stock:true,badge:'Новинка',description:'Компактное растение с розовыми прожилками и яркой листвой.'},
 {id:31,name:'Папоротник нефролепис мини',price:780,category:'plant',image:'assets/terrarium-03.jpg',stock:true,description:'Молодой миниатюрный папоротник для просторных флорариумов.'},
 {id:32,name:'Селагинелла изумрудная',price:690,category:'plant',image:'assets/terrarium-06.jpg',stock:false,description:'Текстурное влаголюбивое растение с плотной кружевной зеленью.'},
 {id:33,name:'Пилея мелколистная',price:560,category:'plant',image:'assets/terrarium-05.jpg',stock:true,description:'Воздушное почвопокровное растение для переднего плана композиции.'},
 {id:34,name:'Фикус пумила мини',price:720,category:'plant',image:'assets/terrarium-08.jpg',stock:true,description:'Стелющийся мини-фикус, быстро формирующий зелёный рельеф.'},
 {id:35,name:'Пеперомия «Пикси»',price:850,category:'plant',image:'assets/terrarium-01.jpg',stock:true,badge:'Хит',description:'Компактная пеперомия с плотными листьями и аккуратной формой.'},
 {id:36,name:'Мох сфагнум, 250 г',price:540,category:'plant',image:'assets/terrarium-07.jpg',stock:true,description:'Подготовленный сфагнум для удержания влаги и укладки субстрата.'},
 {id:37,name:'Мох лесной пластовой',price:690,category:'plant',image:'assets/terrarium-07.jpg',stock:true,description:'Плотный живой ковёр для оформления рельефа и закрытия грунта.'},
 {id:38,name:'Асплениум мини',price:890,category:'plant',image:'assets/terrarium-03.jpg',stock:false,description:'Яркий папоротник с волнистыми листьями для высокой композиции.'},
 {id:39,name:'Бегония декоративная мини',price:940,category:'plant',image:'assets/terrarium-02.jpg',stock:true,description:'Небольшая бегония с выразительной фактурой и рисунком листа.'},
 {id:40,name:'Композиция растений «Трио»',price:1750,category:'plant',image:'assets/terrarium-04.jpg',stock:true,description:'Три совместимых растения, подобранных для одного флорариума.'},
 {id:41,name:'Набор «Первый флорариум»',price:2500,category:'kit',image:'assets/terrarium-05.jpg',stock:true,badge:'Для новичков',description:'Базовый комплект с сосудом, материалами и пошаговой инструкцией.'},
 {id:42,name:'Набор «Тропический остров»',price:3900,category:'kit',image:'assets/terrarium-06.jpg',stock:true,description:'Набор для пышной тропической композиции среднего размера.'},
 {id:43,name:'Набор «Мох и камень»',price:3100,category:'kit',image:'assets/terrarium-07.jpg',stock:true,description:'Всё необходимое для лаконичного мшистого ландшафта.'},
 {id:44,name:'Набор «Семейный мастер-класс»',price:5200,category:'kit',image:'assets/terrarium-08.jpg',stock:false,description:'Два комплекта материалов для совместной домашней сборки.'},
 {id:45,name:'Набор «Мини-сад на стол»',price:2800,category:'kit',image:'assets/terrarium-01.jpg',stock:true,description:'Компактный набор для небольшой композиции на рабочем столе.'},
 {id:46,name:'Набор «Лесная история»',price:4300,category:'kit',image:'assets/terrarium-02.jpg',stock:true,badge:'Хит',description:'Расширенный комплект с растениями, декором и фигурками.'},
 {id:47,name:'Набор «Зелёный подарок»',price:3600,category:'kit',image:'assets/terrarium-03.jpg',stock:true,description:'Подарочная коробка с материалами и красивой печатной инструкцией.'},
 {id:48,name:'Набор «Сад под куполом»',price:4900,category:'kit',image:'assets/terrarium-04.jpg',stock:true,description:'Комплект для закрытого сада под высоким стеклянным куполом.'},
 {id:49,name:'Набор «Папоротниковая долина»',price:4600,category:'kit',image:'assets/terrarium-05.jpg',stock:false,description:'Набор с несколькими видами папоротника для объёмной композиции.'},
 {id:50,name:'Набор «Большая экосистема»',price:7900,category:'kit',image:'assets/terrarium-06.jpg',stock:true,badge:'Премиум',description:'Большой набор со стеклом, растениями, инструментами и декором.'}
];
const articles={care:{title:'Как сохранить микроклимат внутри флорариума',tag:'Уход · 8 минут',image:'assets/terrarium-03.jpg',body:['Закрытый флорариум сам поддерживает влажность, но всё равно любит внимание. Поставьте его в светлое место без прямого полуденного солнца.','Если на стенках постоянно много конденсата, приоткройте крышку на несколько часов. Поливайте только после того, как грунт заметно подсохнет — обычно достаточно нескольких ложек воды раз в две–четыре недели.','Удаляйте сухие листья чистыми ножницами и время от времени поворачивайте композицию к свету другой стороной.']},place:{title:'Где поставить мини-сад, чтобы он радовал каждый день',tag:'Вдохновение · 5 минут',image:'assets/terrarium-08.jpg',body:['Флорариум хорошо чувствует себя на рабочем столе, прикроватной тумбе или открытой полке недалеко от окна. Главное — рассеянный свет и стабильная температура.','Не ставьте сосуд рядом с батареей, кондиционером или на подоконник под прямые солнечные лучи: стекло быстро нагревается.','Выберите место на уровне глаз — так будет интереснее наблюдать, как развивается ваша маленькая экосистема.']}};
Object.assign(articles,{watering:{title:'Как правильно поливать мини-сад',tag:'Уход · 6 минут',image:'assets/terrarium-04.jpg',body:['Главное правило флорариума — лучше немного недолить, чем превратить грунт в болото. В закрытом сосуде вода циркулирует и расходуется медленно.','Используйте шприц или лейку с тонким носиком. Добавляйте воду небольшими порциями ближе к корням, не заливая листья и стенки сосуда.','После полива понаблюдайте за грунтом несколько дней. Следующий полив нужен только после заметного просыхания верхнего слоя.']},moss:{title:'Всё о живом мхе',tag:'Растения · 7 минут',image:'assets/terrarium-07.jpg',body:['Живой мох создаёт рельеф, удерживает влагу и делает композицию похожей на настоящий лес. Ему нравится рассеянный свет и высокая влажность.','Не прижимайте мох слишком плотно к грунту и не оставляйте на нём крупные капли. Для увлажнения лучше использовать мелкий распылитель.','Побуревшие участки можно аккуратно удалить, а освободившееся место закрыть свежим фрагментом.']},light:{title:'Сколько света нужно растениям',tag:'Советы · 4 минуты',image:'assets/terrarium-02.jpg',body:['Большинству растений во флорариуме нужен яркий, но рассеянный свет. Идеально подходит место в метре от восточного или западного окна.','Прямое солнце быстро нагревает стекло и может обжечь листья. Если света мало, используйте небольшую фитолампу с таймером на 8–10 часов.','Раз в неделю поворачивайте сосуд на четверть оборота, чтобы растения развивались равномерно.']},diy:{title:'Собираем флорариум с нуля',tag:'Мастер-класс · 10 минут',image:'assets/terrarium-05.jpg',body:['Сначала промойте сосуд и уложите дренаж. Добавьте слой угля, затем подходящий рыхлый грунт и сформируйте будущий рельеф.','Высадите растения от крупных к мелким, оставляя место для роста. Закройте свободный грунт мхом и добавьте немного природного декора.','Аккуратно полейте композицию, очистите стекло и первые две недели внимательно следите за конденсатом.']}});
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
let cart=readStore('botanica-cart',[]),favorites=readStore('botanica-favorites',[]),visibleLimit=9,currentCategory='all',searchTerm='';
function readStore(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function writeStore(key,value){localStorage.setItem(key,JSON.stringify(value))}
function filtered(){let list=products.filter(p=>currentCategory==='all'||p.category===currentCategory);const checked=$$('.filter-category:checked').map(x=>x.value);if(checked.length)list=list.filter(p=>checked.includes(p.category));const min=+$('#priceMin').value||0,max=+$('#priceMax').value||Infinity;if($('#stockOnly').checked)list=list.filter(p=>p.stock);list=list.filter(p=>p.price>=min&&p.price<=max&&p.name.toLowerCase().includes(searchTerm));const sort=$('#sortSelect').value;if(sort==='asc')list.sort((a,b)=>a.price-b.price);if(sort==='desc')list.sort((a,b)=>b.price-a.price);if(sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name,'ru'));return list}
function productCard(p){const inCart=cart.some(x=>x.id===p.id),liked=favorites.includes(p.id);return `<article class="product-card"><div class="product-image"><button class="image-open" data-quick="${p.id}" aria-label="Открыть ${p.name}" style="position:absolute;inset:0;border:0;background:transparent;z-index:1"></button><img src="${p.image}" alt="${p.name}" loading="lazy">${p.badge?`<span class="badge">${p.badge}</span>`:''}<button class="quick-button" data-quick="${p.id}" aria-label="Быстрый просмотр ${p.name}" style="z-index:2">⌕</button><button class="favorite-button ${liked?'active':''}" data-favorite="${p.id}" aria-label="${liked?'Убрать из избранного':'Добавить в избранное'}" style="z-index:2">${liked?'♥':'♡'}</button></div><div class="product-info"><span class="product-status ${p.stock?'':'out'}">${p.stock?'В наличии':'Изготовим под заказ'}</span><button class="product-title-button" data-quick="${p.id}">${p.name}</button><div class="product-bottom"><b>${money(p.price)}</b><button class="add-button ${inCart?'in-cart':''} ${p.stock?'':'notify-button'}" data-add="${p.id}" aria-label="${p.stock?'Добавить в корзину':'Заказать изготовление'}">${inCart?'В корзине':p.stock?'+':'Заказать'}</button></div></div></article>`}
function renderProducts(){const list=filtered();$('#resultCount').textContent=`Найдено: ${list.length}`;$('#productGrid').innerHTML=list.length?list.slice(0,visibleLimit).map(productCard).join(''):'<div class="empty-state"><span>⌕</span><b>Ничего не нашли</b><p>Измените фильтры или сбросьте параметры.</p><button class="button button--green" id="emptyReset">Сбросить фильтры</button></div>';$('#loadMore').style.display=list.length>visibleLimit?'flex':'none';bindProductActions();$('#emptyReset')?.addEventListener('click',resetFilters)}
function bindProductActions(){$$('[data-add]').forEach(b=>b.onclick=e=>{e.stopPropagation();addToCart(+b.dataset.add)});$$('[data-quick]').forEach(b=>b.onclick=e=>{e.stopPropagation();showQuick(+b.dataset.quick)});$$('[data-favorite]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFavorite(+b.dataset.favorite)})}
function addToCart(id,qty=1){const found=cart.find(x=>x.id===id);found?found.qty+=qty:cart.push({id,qty});saveCart();showToast('Товар добавлен в корзину')}
function changeQty(id,delta){const line=cart.find(x=>x.id===id);if(!line)return;line.qty+=delta;if(line.qty<=0)cart=cart.filter(x=>x.id!==id);saveCart()}
function saveCart(){writeStore('botanica-cart',cart);renderCart();renderProducts()}
function renderCart(){const lines=cart.map(x=>({...products.find(p=>p.id===x.id),qty:x.qty})),amount=lines.reduce((a,x)=>a+x.qty,0),subtotal=lines.reduce((a,p)=>a+p.price*p.qty,0),delivery=subtotal>=7000||!lines.length?0:490,total=subtotal+delivery;$('#cartCount').textContent=amount;$('#cartItems').innerHTML=lines.length?lines.map(p=>`<div class="cart-line"><img src="${p.image}" alt=""><div><p>${p.name}</p><small>${money(p.price)}</small><div class="cart-line-controls"><button data-minus="${p.id}" aria-label="Уменьшить">−</button><b>${p.qty}</b><button data-plus="${p.id}" aria-label="Увеличить">+</button></div></div><button class="cart-line-remove" data-remove="${p.id}" aria-label="Удалить">×</button></div>`).join(''):'<div class="empty-state"><span>♧</span><b>Корзина пока пуста</b><p>Добавьте живую композицию из каталога.</p><button class="button button--green" id="cartToCatalog">Выбрать товары</button></div>';$('#cartSubtotal').textContent=money(subtotal);$('#cartDelivery').textContent=lines.length?(delivery?money(delivery):'Бесплатно'):'—';$('#cartTotal').textContent=money(total);updateCheckoutTotal();const pct=Math.min(100,Math.round(subtotal/7000*100));$('#deliveryBar').style.width=pct+'%';$('#deliveryPercent').textContent=pct+'%';$('#deliveryText').textContent=subtotal>=7000?'Бесплатная доставка доступна':`До бесплатной доставки — ${money(7000-subtotal)}`;$$('[data-minus]').forEach(b=>b.onclick=()=>changeQty(+b.dataset.minus,-1));$$('[data-plus]').forEach(b=>b.onclick=()=>changeQty(+b.dataset.plus,1));$$('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.id!==+b.dataset.remove);saveCart();showToast('Товар удалён')});$('#cartToCatalog')?.addEventListener('click',goCatalog)}
function updateCheckoutTotal(){const subtotal=cart.reduce((sum,line)=>{const p=products.find(x=>x.id===line.id);return sum+(p?.price||0)*line.qty},0),method=$('#checkoutForm input[name="delivery"]:checked')?.value,delivery=method==='courier'&&subtotal<7000&&subtotal>0?490:0;$('#checkoutTotal').textContent=money(subtotal+delivery)}
function toggleFavorite(id){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];writeStore('botanica-favorites',favorites);renderFavorites();renderProducts();showToast(favorites.includes(id)?'Добавлено в избранное':'Удалено из избранного')}
function renderFavorites(){const list=favorites.map(id=>products.find(p=>p.id===id)).filter(Boolean);$('#favoriteCount').textContent=list.length;$('#favoriteItems').innerHTML=list.length?list.map(p=>`<div class="cart-line favorite-line"><img src="${p.image}" alt=""><div><p>${p.name}</p><small>${money(p.price)}</small><button class="button button--green" data-fav-add="${p.id}">В корзину</button></div><button class="cart-line-remove" data-fav-remove="${p.id}" aria-label="Удалить">×</button></div>`).join(''):'<div class="empty-state"><span>♡</span><b>Здесь пока пусто</b><p>Нажмите на сердце в карточке товара, чтобы сохранить его.</p></div>';$$('[data-fav-add]').forEach(b=>b.onclick=()=>addToCart(+b.dataset.favAdd));$$('[data-fav-remove]').forEach(b=>b.onclick=()=>toggleFavorite(+b.dataset.favRemove))}
function showQuick(id){const p=products.find(x=>x.id===id),liked=favorites.includes(id);$('#quickContent').innerHTML=`<div class="quick-grid"><img src="${p.image}" alt="${p.name}"><div class="quick-copy"><p class="eyebrow">${p.stock?'В наличии':'Изготовим за 3–5 дней'}</p><h2 id="quickTitle">${p.name}</h2><p>${p.description}</p><p>В комплекте: композиция, инструкция по уходу и безопасная упаковка.</p><p class="price">${money(p.price)}</p><div style="display:flex;gap:10px"><button class="button button--green" id="quickAdd">${p.stock?'Добавить в корзину':'Заказать изготовление'}</button><button class="button" id="quickFavorite" style="border:1px solid var(--line);background:transparent">${liked?'♥ В избранном':'♡ В избранное'}</button></div></div></div>`;$('#quickAdd').onclick=()=>{addToCart(id);closePanels()};$('#quickFavorite').onclick=()=>{toggleFavorite(id);showQuick(id)};openPanel($('#quickModal'))}
function openArticle(key){const a=articles[key];$('#journalModal').classList.remove('open');$('#articleContent').innerHTML=`<button class="article-back" id="articleBack">← Все материалы</button><img src="${a.image}" alt=""><p class="eyebrow" style="margin-top:24px">${a.tag}</p><h2 id="articleTitle">${a.title}</h2>${a.body.map(p=>`<p>${p}</p>`).join('')}`;$('#articleBack').onclick=()=>{$('#articleModal').classList.remove('open');openPanel($('#journalModal'))};openPanel($('#articleModal'))}
function renderSearch(){const value=$('#searchInput').value.trim().toLowerCase(),matches=products.filter(p=>p.name.toLowerCase().includes(value)).slice(0,4);$('.search-panel>p').textContent=value?`Найдено товаров: ${matches.length}`:'Начните вводить название товара';$('#searchResults').innerHTML=value?matches.map(p=>`<button class="search-result" data-search-product="${p.id}"><img src="${p.image}" alt=""><b>${p.name}</b><small>${money(p.price)}</small></button>`).join(''):'';$$('[data-search-product]').forEach(b=>b.onclick=()=>{closePanels();showQuick(+b.dataset.searchProduct)})}
function chooseCategory(category){currentCategory=category;visibleLimit=9;searchTerm='';$('#searchInput').value='';$$('.filter-category').forEach(x=>x.checked=false);$$('.category').forEach(x=>x.classList.toggle('active',x.dataset.category===category));renderProducts();$('#shopDropdown').classList.remove('open');$('#shopMenuButton').setAttribute('aria-expanded','false');$('.primary-nav').classList.remove('open');document.querySelector('#catalog').scrollIntoView()}
function resetFilters(){$$('.filters input').forEach(x=>{if(x.type==='checkbox')x.checked=false;else x.value=''});currentCategory='all';searchTerm='';visibleLimit=9;$('#searchInput').value='';$$('.category').forEach(x=>x.classList.toggle('active',x.dataset.category==='all'));renderProducts()}
function goCatalog(){closePanels();document.querySelector('#catalog').scrollIntoView()}
function openPanel(el){$('#overlay').classList.add('visible');el.classList.add('open');document.body.classList.add('locked');setTimeout(()=>el.querySelector('input,button')?.focus(),80)}
function closePanels(){$$('.drawer.open,.modal.open,.search-panel.open,.filters.open').forEach(x=>x.classList.remove('open'));$('#overlay').classList.remove('visible');document.body.classList.remove('locked')}
function showToast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
$$('[data-open]').forEach(b=>b.onclick=()=>{const map={cart:$('#cartDrawer'),favorites:$('#favoritesDrawer'),callback:$('#callbackModal'),search:$('#searchPanel'),journal:$('#journalModal')};if(b.dataset.open==='search')setTimeout(()=>$('#searchInput').focus(),100);openPanel(map[b.dataset.open])});$$('[data-close]').forEach(b=>b.onclick=closePanels);$('#overlay').onclick=closePanels;document.addEventListener('keydown',e=>{if(e.key==='Escape')closePanels()});
$$('.category').forEach(b=>b.onclick=()=>chooseCategory(b.dataset.category));$$('[data-shop-category]').forEach(b=>b.onclick=()=>chooseCategory(b.dataset.shopCategory));$('#shopMenuButton').onclick=e=>{e.stopPropagation();const open=$('#shopDropdown').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))};document.addEventListener('click',e=>{if(!e.target.closest('.shop-menu')){$('#shopDropdown').classList.remove('open');$('#shopMenuButton').setAttribute('aria-expanded','false')}});
$('#sortSelect').onchange=renderProducts;$('#applyFilters').onclick=()=>{visibleLimit=9;renderProducts();closePanels()};$$('.filter-category,#stockOnly').forEach(x=>x.onchange=renderProducts);$('#priceMin').oninput=$('#priceMax').oninput=()=>{clearTimeout(window.priceTimer);window.priceTimer=setTimeout(renderProducts,250)};$('#resetFilters').onclick=resetFilters;$('#loadMore').onclick=()=>{visibleLimit+=9;renderProducts()};$('#filterToggle').onclick=()=>openPanel($('#filters'));$('#filterClose').onclick=closePanels;
$('#searchInput').oninput=renderSearch;$('#searchInput').onkeydown=e=>{if(e.key==='Enter'){searchTerm=e.target.value.trim().toLowerCase();closePanels();renderProducts();document.querySelector('#catalog').scrollIntoView()}};
$('#themeButton').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('botanica-theme',document.body.classList.contains('dark')?'dark':'light');$('#themeButton').textContent=document.body.classList.contains('dark')?'☀':'☾'};if(localStorage.getItem('botanica-theme')==='dark'){$('body').classList.add('dark');$('#themeButton').textContent='☀'}
$('#menuButton').onclick=()=>$('.primary-nav').classList.toggle('open');$$('.primary-nav>a').forEach(a=>a.onclick=()=>$('.primary-nav').classList.remove('open'));$('#favoritesToCatalog').onclick=goCatalog;
$('#callbackForm').onsubmit=e=>{e.preventDefault();e.target.reset();closePanels();showToast('Спасибо! Мы скоро свяжемся с вами')};$('#subscribeForm').onsubmit=e=>{e.preventDefault();e.target.reset();showToast('Подписка оформлена')};
$('#checkoutButton').onclick=()=>{if(!cart.length)return showToast('Корзина пока пуста');closePanels();$('#checkoutForm').style.display='block';$('#orderSuccess').classList.remove('visible');updateCheckoutTotal();openPanel($('#checkoutModal'))};$$('#checkoutForm input[name="delivery"]').forEach(x=>x.onchange=updateCheckoutTotal);$('#checkoutForm').onsubmit=e=>{e.preventDefault();const order='BT-'+String(Date.now()).slice(-6),record={order,date:new Date().toISOString(),items:cart,total:$('#checkoutTotal').textContent};const orders=readStore('botanica-orders',[]);orders.push(record);writeStore('botanica-orders',orders);cart=[];saveCart();e.target.style.display='none';$('#orderNumber').textContent=order;$('#orderSuccess').classList.add('visible')};$('#successClose').onclick=goCatalog;
$$('[data-article]').forEach(el=>{el.onclick=()=>openArticle(el.dataset.article);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openArticle(el.dataset.article)}}});
$('#acceptCookie').onclick=()=>{localStorage.setItem('botanica-cookie','accepted');$('#cookieBanner').classList.remove('visible')};if(!localStorage.getItem('botanica-cookie'))setTimeout(()=>$('#cookieBanner').classList.add('visible'),700);
renderProducts();renderCart();renderFavorites();
